sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t shiincs/docker-simple -f Dockerfile.dev ./

script:
  - docker run -e CI=true shiincs/docker-simple npm run test -- --coverage

after_success:
  - echo "Test success"